#lang racket

;; ----------------------------------------------------------------------
;; Problem 2: Even Fibonacci numbers
;; https://projecteuler.net/problem=2

;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.

;; Answer: 4613732
;; ----------------------------------------------------------------------

;; This approach sacrifices the generality of using a pre-existing
;; fibonacci function and combines the fibonacci computation with the
;; filtering & summing.

(define (sum-even-fibs max)
  (let fibs ([f1 1] [f2 2] [sum 0])
    (if (> f2 max)
        sum
        (fibs f2 (+ f1 f2) (+ sum (if (even? f2) f2 0))))))

(display (sum-even-fibs 4000000))
